### ISSUE TITLE
CD?

### ISSUE THREAD

**Issue by StevenTCramer** [replaysMike/TypeSupport#16]
I see Appvoyer badge but I don't see any yml nor any Nuget release based on the last PR.  Is the Nuget piece currently manual?

I'm pushing new Blazor-State out as soon as your Nuget is updated.  And I am going on Blazor StateHasChange, Ed Charbeneau Twitch show, to talk about it "Will give you a plug for AnyClone" also.

Thanks again.

**Comment by replaysMike** [comment]
correct Nuget deployments are currently manual. The Appveyor yml configuration wasn't kept in the repo as I was using multiple CI systems at the time and didn't want to litter the repo. It's probably worthwhile for me to move the configuration at this point to the repo so it can be managed by others as well, and I can automate the Nuget deployments as part of that configuration.

I'll push a nuget update right now, and then work on adding configuration for all Any* package repos. Thanks!

**Comment by replaysMike** [comment]
Version TypeSupport.1.0.73 should now be published, should show up in the feed within a couple minutes

**Comment by StevenTCramer** [comment]
You rock mate!  Thanks!
